name: RickFueyo
favicon: null
layout_spectrum: 0.37117696227505803
typography_spectrum: 0.6537958392873406
title: 'My passion is teaching; local marketing to SMBs, soccer to little footies, and life to my children with my amazing wife.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5c5c5c'
    - '#969696'
    - '#1ca5df'
  brandStrength: 0.8691061208955944
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
